language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest
# command to run tests
script: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pytest test_py3.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pytest test_py2.py; fi
